### ISSUE TITLE
Utility for executing caps2esc automatically when keyboard layout changes

### ISSUE THREAD

**Issue by oblitum** [alexandre/caps2esc#2]
This script line on Ubuntu is able to make caps2esc execute any time the keyboard layout changes:

```
dconf watch /org/gnome/desktop/input-sources/current | xargs -L 2 caps2esc &
```

Notice the `&` is creating a deamon.

This could be embedded in the setup or mentioned in README somehow.

Source: http://unix.stackexchange.com/a/114757/42313

**Comment by alexandre** [comment]
I think add a mention in README is better, let's give the decision to the Ubuntu user. Can you add it?

Thanks.

**Comment by oblitum** [comment]
As soon as possible.
